"""Storage interface. Two implementations: LocalStore (JSON file + disk, used for
mock mode and tests) and SupabaseStore (Postgres + Storage on the brain2 project)."""
from __future__ import annotations

from typing import Any, Protocol

TABLES = ("users", "scans", "reports", "audit_events", "support_tickets", "auth_tokens")


class Store(Protocol):
    name: str

    async def start(self) -> None: ...
    async def stop(self) -> None: ...
    async def insert(self, table: str, row: dict) -> dict: ...
    async def get(self, table: str, id: str) -> dict | None: ...
    async def update(self, table: str, id: str, patch: dict) -> dict: ...
    async def delete(self, table: str, id: str) -> None: ...
    async def select(self, table: str, where: dict[str, Any] | None = None, order: str | None = None,
                     desc: bool = False, limit: int | None = None) -> list[dict]: ...
    async def put_file(self, path: str, data: bytes, content_type: str) -> None: ...
    async def get_file(self, path: str) -> bytes | None: ...
    async def delete_file(self, path: str) -> None: ...
    async def audit_append(self, event: dict) -> dict: ...
    async def audit_list(self, scan_id: str | None = None, limit: int | None = None) -> list[dict]: ...
